### PR TITLE
add note about override host to make adoption possible

### PR DESCRIPTION
**Pull request by DOliana**
Description: add description of required setting to allow adoption when running unifi controller in a docker container
Benefits of this PR and context: less headaches for new users
How Has This Been Tested? read it, done it
Source / References: issue #38

### CODE REVIEW

**Comment by Roxedus** [comment]
Please use the pull request template. If you did, and read the file it told you to read, you would see that your pull request is invalid.

**Comment by DOliana** [comment]
@Roxedus I read it and decided to not use it, since I am only adding a sentence to the readme, which is self-explanatory. This fixes an issue which has been open for 8 months.

Nonetheless, here you go:
Description: add description of required setting to allow adoption when running unifi controller in a docker container
Benefits of this PR and context: less headaches for new users
How Has This Been Tested? read it, done it
Source / References: issue #38

**Comment by aptalca** [comment]
@DOliana please read it again as there is no option such as `decided not to use it`

**Comment by Roxedus** [comment]
My comment was aimed towards the fact that editing the readme wont actually change the readme. It tells you to read the contributing file, which states why, and how you can make the change. https://github.com/linuxserver/docker-unifi-controller/blob/master/.github/CONTRIBUTING.md#readme

**Comment by DOliana** [comment]
OK, so what should happen now?
Accoring to the readme (which was not posted previously) an issue should be created for changes in the README, which has been done (#38) 6 months ago with nobody changing the readme (If others run into the same issues I am having, I cannot blame them).

To be honest I just would like to help other people out there and am feeling that I am hindered as much as possible to do it. My last try now is to edit the PR-comment.

**Comment by Roxedus** [comment]
Edit the readme vars file, that way the changes to the readme actually sticks

**Comment by DOliana** [comment]
Thank you @Roxedus  for pointing me in the correct direction. I reverted the change to the readme and moved it to the yaml-file.

**Comment by TheSpad** [comment]
Resolved via #75

**Pull request closed without merging**
